version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Validating Python syntax..."

      - python -m py_compile lambda/lambda_function.py
      - python -m py_compile scripts/extract_earthquake_data.py
      - python -m py_compile scripts/upload_to_s3.py
      - python -m py_compile scripts/run_pipeline.py

  build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - lambda/**
    - scripts/**
    - requirements.txt
    - README.md
    - buildspec.yml

cache:
  paths:
    - '/root/.cache/pip/**/*'