name: EarthPulse CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate Lambda Syntax
        run: |
          python -m py_compile lambda/lambda_function.py

      - name: Validate Extraction Script
        run: |
          python -m py_compile scripts/extract_earthquake_data.py

      - name: Validate Upload Script
        run: |
          python -m py_compile scripts/upload_to_s3.py

      - name: Validate Pipeline Runner
        run: |
          python -m py_compile scripts/run_pipeline.py

      - name: CI Completed
        run: echo "EarthPulse CI Passed Successfully!"